version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.3.1-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-rugal-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn lint
      - run: yarn e2e
      - run: yarn build --prod
      - save_cache:
          key: v1-rugal-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
